### PR TITLE
update version to 8.8.3

### PR DESCRIPTION
**Pull request by kurtsansom**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

updated to version 8.8.3
 <code>@<space/>conda-forge-admin, please rerender</code>

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Hi, thanks!

Sorry, why is there version 8.3.3 and version 8.3.3a? and which one should we use here?

**Comment by jcupitt** [comment]
Hello, it says in the comment: 

> vips-8.8.3a.tar.gz is just vips-8.8.3.tar.gz, but with a single test removed to help it pass with a wider range of librsvg versions.

**Comment by sebastian-luna-valero** [comment]
Apologies, I took the tarball in a rush and didn't read the comments.

**Comment by sebastian-luna-valero** [comment]
Hi,

With version 8.3.3, I get:
```
testing blankpage.svg svgload ... save / load difference is 80.000000
FAIL test_formats.sh (exit status: 1)
```

**Comment by jcupitt** [comment]
Yes, that's the test I removed in 8.8.3a, I think. 

librsvg changed the way they do coordinate rounding, so all images are displaced by 0.5 pixels. It's enough to break tests that compare against a standard.

**Comment by sebastian-luna-valero** [comment]
Thanks, that fixes it.

However, the Linux build is failing randomly with an error that I don't understand:
```
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... 
ClobberWarning: Conda was asked to clobber an existing path.
  source path: /opt/conda/pkgs/libvips-8.8.3-h49d8aaf_0/lib//
  target path: /home/conda/feedstock_root/build_artifacts/libvips_1573504292703/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib//



done
ERROR:conda.core.link:An error occurred while installing package 'local::libvips-8.8.3-h49d8aaf_0'.
ERROR conda.core.link:_execute(700): An error occurred while installing package 'local::libvips-8.8.3-h49d8aaf_0'.
Rolling back transaction: ...working... done
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 469, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 460, in execute
    verify=args.verify, variants=args.variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2350, in build_tree
    test(pkg, config=metadata.config.copy(), stats=stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2155, in test
    is_conda=metadata.name() == 'conda')
  File "/opt/conda/lib/python3.7/site-packages/conda_build/environ.py", line 868, in create_env
    execute_actions(actions, index)
  File "/opt/conda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/conda/plan.py", line 321, in execute_actions
    execute_instructions(plan, index, verbose)
  File "/opt/conda/lib/python3.7/site-packages/conda/plan.py", line 533, in execute_instructions
    cmd(state, arg)
  File "/opt/conda/lib/python3.7/site-packages/conda/instructions.py", line 73, in UNLINKLINKTRANSACTION_CMD
    unlink_link_transaction.execute()
  File "/opt/conda/lib/python3.7/site-packages/conda/core/link.py", line 249, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "/opt/conda/lib/python3.7/site-packages/conda/core/link.py", line 716, in _execute
    rollback_excs,
conda.CondaMultiError: [Errno 21] Is a directory: '/opt/conda/pkgs/libvips-8.8.3-h49d8aaf_0/lib//'
()
```

**Comment by jcupitt** [comment]
This error is very suspicious:

```
conda.CondaMultiError: [Errno 21] Is a 
   directory: '/opt/conda/pkgs/libvips-8.8.3-h49d8aaf_0/lib//'
```

Why is there a double slash (`//`) at the end? Perhaps an environment variable has not been set?

**Comment by sebastian-luna-valero** [comment]
It looks to me like a conda error, but didn't find a similar problem/solution out there.

I am re-running tests before we ask for help to conda/conda-forge.

**Comment by sebastian-luna-valero** [comment]
@conda-forge-admin, please rerender

**Comment by sebastian-luna-valero** [comment]
xref: https://github.com/conda-forge/pylint-feedstock/issues/27

**Comment by sebastian-luna-valero** [comment]
@conda-forge/core please help

**Comment by jcupitt** [comment]
It looks like the current conda package has stopped working too, somehow:

```
$ conda create --name test python=3 pyvips
...
$ conda activate test
(test) $ which python
/home/john/miniconda3/envs/test/bin/python
(test) $ python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
Segmentation fault (core dumped)
```

It seems to be failing to `dlopen()` libgobject, though the library is present in `/home/john/miniconda3/envs/test/lib`.

**Comment by sebastian-luna-valero** [comment]
@conda-forge-admin, please rerender

**Comment by sebastian-luna-valero** [comment]
ping conda-forge/core

**Comment by sebastian-luna-valero** [comment]
ping @conda-forge/core

**Comment by ocefpaf** [comment]
> ping @conda-forge/core

Why? Do you need help with something?

**Comment by sebastian-luna-valero** [comment]
Yes, please. We cannot re-render this feedstock.

**Comment by ocefpaf** [comment]
> Yes, please. We cannot re-render this feedstock.

Did you try following the docs on the [bot comment](https://github.com/conda-forge/libvips-feedstock/pull/4#issuecomment-558750557) regarding re-rendering it locally?

**Comment by sebastian-luna-valero** [comment]
I will try that, thanks. 

Are you aware of issues with the conda-forge-webservice ?

**Comment by ocefpaf** [comment]
> Are you aware of issues with the conda-forge-webservice ?

It is a websevice that may be down due to updates in the pinning package or conda-smithy. That is why the local re-render is always an option.

**Comment by sebastian-luna-valero** [comment]
@ocefpaf 

We are getting the following error messages:
```
conda.CondaMultiError: [Errno 21] Is a directory: '/opt/conda/pkgs/libvips-8.8.1-h49d8aaf_1/lib//'
```
On this PR and on https://github.com/conda-forge/libvips-feedstock/pull/5

Any suggestions?

**Comment by mbargull** [comment]
`libtool` runs `ldconfig` and the latter does something funky with the libraries from `gstreamer-orc`, creating links named `'\'` and `$'\003'`.
Interestingly enough, I couldn't reproduce that on my host OS but could -- albeit with the same `glibc` version -- in a `fedora:31` container:
```sh
~ >>>  podman run --rm -it centos:6 sh -c 'cd /tmp && curl -sL https://anaconda.org/conda-forge/gstreamer-orc/0.4.31/download/linux-64/gstreamer-orc-0.4.31-h516909a_0.tar.bz2 | tar -xjf- lib/liborc-test-0.4.so.0.31.0 && ldconfig --version | head -n1 && ldconfig -vnN ./lib'
ldconfig (GNU libc) 2.12
./lib:
	\ -> liborc-test-0.4.so.0.31.0 (changed)
~ >>>  podman run --rm -it fedora:31 sh -c 'dnf -qy install bsdtar && cd /tmp && curl -sL https://anaconda.org/conda-forge/gstreamer-orc/0.4.31/download/linux-64/gstreamer-orc-0.4.31-h516909a_0.tar.bz2 | bsdtar -xf- lib/liborc-test-0.4.so.0.31.0 && ldconfig --version | head -n1 && ldconfig -vnN ./lib'
ldconfig (GNU libc) 2.30
./lib:
	\ -> liborc-test-0.4.so.0.31.0 (changed)
~ >>>  podman run --rm -it archlinux/base sh -c 'cd /tmp && curl -sL https://anaconda.org/conda-forge/gstreamer-orc/0.4.31/download/linux-64/gstreamer-orc-0.4.31-h516909a_0.tar.bz2 | bsdtar -xf- lib/liborc-test-0.4.so.0.31.0 && ldconfig --version | head -n1 && ldconfig -vnN ./lib'              
ldconfig (GNU libc) 2.30
./lib:
	liborc-test-0.4.so.0 -> liborc-test-0.4.so.0.31.0 (changed)
```

**Comment by mbargull** [comment]
xref: https://github.com/conda-forge/gstreamer-orc-feedstock/issues/3

**Comment by sebastian-luna-valero** [comment]
Closing in favor of https://github.com/conda-forge/libvips-feedstock/pull/8

**Pull request closed without merging**
