### PR TITLE
Rerender using conda-smithy to fix upload

### PR DESCRIPTION
**Pull request by frmdstryr**
I forgot to "rerender"... so the upload is failing.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by frmdstryr** [comment]
@conda-forge-admin, please rerender

**Comment by frmdstryr** [comment]
@jcupitt sorry for the noise, I forgot/didn't know about needing to "rerender" the feedstock which (I think) is why the upload failed. This PR just changes the build number and asked the bot to rerender it. Can you merge this again?

**Comment by jcupitt** [comment]
It seems to be failing with package conflicts :(

**Comment by frmdstryr** [comment]
... yeah, I'll see if I can resolve them.

**Comment by frmdstryr** [comment]
Ok it's passing now... hopefully the upload works this time.

**Comment by frmdstryr** [comment]
@jcupitt can you review this again please, I bumped the versions that changed back down.

**Comment by jcupitt** [comment]
LGTM! Well done @frmdstryr !

**Comment by frmdstryr** [comment]
Looks like it worked this time... thank you!

**Pull request merged**
