### PR TITLE
Make sure imagemagick < 7.0.9

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
@conda-forge-admin, please rerender

**Comment by sebastian-luna-valero** [comment]
@jcupitt 

We are facing the same issues here as in #4 

* Linux builds fail with the same error
* OSX builds fail with the make check (`testing blankpage.svg svgload ... save / load difference is 80.000000`)

While conda-forge/core takes a look at the Linux issue, could you please upload an equivalent `8.8.1a` release, please?

Again, the `blankpage.svg svgload` failed test should be related to a package update, right? Otherwise, it wouldn't have passed the tests when we released `8.8.1`...

**Comment by jcupitt** [comment]
@sebastian-luna-valero OK, I uploaded vips-8.8.1a.tar.gz

Yes, the test failing is because librsvg changed the way they round float pixel coordinates to int.

**Comment by sebastian-luna-valero** [comment]
Thanks @jcupitt 

Do you know by any chance which version librsvg works with the default tests?

Since we are making a new release, I could pin both imagemagick and librsvg for 8.8.1 on this PR.

Or the other way around, do you need to change your tests in libvips to work with the latest librsvg?

**Comment by jcupitt** [comment]
Yes, 8.9 will have a reworked SVG test that's less sensitive to small offsets like this. For now, it's just disabled.

**Comment by sebastian-luna-valero** [comment]
While we find out what's the issue with `gstreamer-orc`, we'll pin it for this release of `libvips`.

**Pull request merged**
