### PR TITLE
update recipe Dec 2020

### PR DESCRIPTION
**Pull request by hmaarrfk**
Closes #17 #18 #19 

Apparently an updated version fixes compilation errors
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=971106

Many image processing librarires have already migrated to newer hdf5. I had to force the migration myself to install this package in conjunction with my other ones.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
it seems many pinnings were due to some unknown issues with particular versions of the library:

https://github.com/conda-forge/libvips-feedstock/pull/5

**Comment by hmaarrfk** [comment]
@conda-forge/help-c-cpp does anybody know why the following error is appearing:

```
dyld: Library not loaded: @rpath/libgobject-2.0.0.dylib
  Referenced from: /Users/runner/miniforge3/conda-bld/libvips_1607387342067/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/libMagickCore-7.Q16HDRI.7.dylib
  Reason: Incompatible library version: libMagickCore-7.Q16HDRI.7.dylib requires version 6501.0.0 or later, but libgobject-2.0.0.dylib provides version 0.0.0
```

**Comment by hmaarrfk** [comment]
glib 2.58 is a pretty old package https://github.com/conda-forge/glib-feedstock/pull/41
https://anaconda.org/conda-forge/glib/files?page=2

**Comment by hmaarrfk** [comment]
@conda-forge/help-osx-arm64 (ok, i know this isn't arm, but I figure you know the most about Apple).

How do we feel about moving the OSX pinning up to 10.10. 10.9 is becoming increasingly harder to support for graphical applications.

**Comment by xhochy** [comment]
@hmaarrfk Not sure why you have bumped `glib` to a much higher version than the pinning here. Keeping it at 2.58 would avoid the OSX update.

**Comment by hmaarrfk** [comment]
@xhochy thanks for chiming in.

Please see the build logs of 467e687 and the error reported in: 
https://github.com/conda-forge/libvips-feedstock/pull/20#issuecomment-740271848

 tschoonj suggested applying the migration. https://github.com/conda-forge/glib-feedstock/pull/77#issuecomment-740399947

Lets see what happens.

**Comment by hmaarrfk** [comment]
This needs: https://github.com/conda-forge/imagemagick-feedstock/pull/162

**Comment by hmaarrfk** [comment]
thanks everybody. this is ready to go now.

**Comment by hmaarrfk** [comment]
@conda-forge/libvips i've added myself as a maintainer to help along if that is ok. 

Let me know if there is antyhing else i can change.

**Comment by hmaarrfk** [comment]
@conda-forge/libvips a review would be greatly appreciated. The previous pinnings stop this package from getting installed smoothly with recent migrations.

**Comment by sebastian-luna-valero** [comment]
Hi @hmaarrfk 

Many thanks for your contribution!

I am happy with the changes and having you on board as a recipe maintainer would be great.

Can I just double check whether @jcupitt is happy before merging?

Best regards,
Sebastian

**Comment by hmaarrfk** [comment]
Thanks @sebastian-luna-valero

**Comment by sebastian-luna-valero** [comment]
Welcome @hmaarrfk !

**Comment by jcupitt** [comment]
Sure, I'm more than happy. Thank you for your hard work!

**Pull request merged**
