### PR TITLE
Replace libgsf with libarchive

### PR DESCRIPTION
**Pull request by frmdstryr**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

For #117

See https://github.com/libvips/libvips/pull/3476

### CODE REVIEW

**Comment by frmdstryr** [comment]
@conda-forge-admin, please rerender

**Review by hmaarrfk — APPROVED** [review]
thx

**Comment by frmdstryr** [comment]
Is the libarchive arm64 build is broken? 
```
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/13.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libarchive.so: error adding symbols: file in wrong format
```

**Comment by hmaarrfk** [comment]
it seems to be finding certain libraries in the "BUILD_PREFIX" which is wrong. not sure why.

**Comment by frmdstryr** [comment]
Thanks!

**Pull request merged**
